import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Flight } from '../types';
import { formatMinutesToHHmm } from './utils';

export const exportToPDF = (flights: Flight[], pilotName: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header - Industrial/Aviation Style
  doc.setFillColor(31, 31, 31);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('LOGBOOK PRO', 14, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('OFFICIAL FLIGHT LOG REPORT', 14, 28);
  
  // Pilot Info
  doc.setTextColor(150, 150, 150);
  doc.text(`PILOT: ${pilotName.toUpperCase()}`, pageWidth - 14, 20, { align: 'right' });
  doc.text(`DATE: ${new Date().toLocaleDateString()}`, pageWidth - 14, 28, { align: 'right' });

  // Summary Metrics
  const totalMinutes = flights.reduce((acc, f) => acc + f.duration, 0);
  const totalFlights = flights.length;
  
  doc.setDrawColor(80, 80, 80);
  doc.line(14, 48, pageWidth - 14, 48);
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text(`${formatMinutesToHHmm(totalMinutes)}`, 14, 58);
  doc.setFontSize(8);
  doc.text('TOTAL HOURS', 14, 63);
  
  doc.setFontSize(14);
  doc.text(`${totalFlights}`, 60, 58);
  doc.setFontSize(8);
  doc.text('SORTIES', 60, 63);

  // Table Data
  const tableData = flights.map(f => [
    new Date(f.date).toLocaleDateString(),
    f.aircraftReg,
    f.aircraftType,
    f.from,
    f.to,
    f.isSimulator ? 'SIM' : 'VFR',
    f.picName,
    formatMinutesToHHmm(f.duration)
  ]);

  autoTable(doc, {
    startY: 75,
    head: [['DATE', 'REG', 'TYPE', 'DEP', 'ARR', 'COND', 'PIC', 'DUR']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [31, 31, 31],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'center'
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
      valign: 'middle'
    },
    columnStyles: {
      7: { halign: 'right', fontStyle: 'bold' }
    },
    didDrawPage: (data) => {
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by Logbook Pro Terminal System | Page ${data.pageNumber}`,
        14,
        doc.internal.pageSize.getHeight() - 10
      );
    }
  });

  doc.save(`Logbook_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const printLogbook = () => {
  window.print();
};
